### ISSUE TITLE
Move the Investigations and Investigation Groups into JSON

### ISSUE THREAD

**Issue by mathew-alex** [ohcnetwork/care#1541]
Move the Investigations and Investigation Groups into a proper JSON like python dict structure to allow easy updates and additions.
The current way is loading data from a string format 
https://github.com/coronasafe/care/blob/master/care/users/management/commands/populate_investigations.py#L9

The investigation list should contain all items from this sheet.
https://docs.google.com/spreadsheets/d/1hN13p-BDbb1Pkl3a8tcVdWFsFxncju2QPfeOEkKh51E/edit#gid=169054315

Both of the below constraints should be valid.
1. An investigation can be associated with multiple investigation groups.
2. Multiple investigations can be under same investigation group.

**Comment by DraKen0009** [comment]
@sainak  I would like to work on this issue.
