### ISSUE TITLE
Respond with an appropriate error message when the email provider is not configured

### ISSUE THREAD

**Issue by sainak** [ohcnetwork/care#1754]
While resetting the password, if the email provider is not configured the user should be notified to contact the admin

**Comment by bodhish** [comment]
@sainak this looks like a good first issue.

**Comment by Sulochan-khadka** [comment]
If the issue still persists , i would like to work on this.

**Comment by praffq** [comment]
@Sulochan-khadka  Since there are no update since past 3 weeks , I'll like to work on it and make a PR to fix this.

**Comment by Sulochan-khadka** [comment]
Sure ... Go ahead @DraKen0009 ... Am working on some other issues ...
