### ISSUE TITLE
Make arm and x86 builds run parallelly

### ISSUE THREAD

**Issue by sainak** [ohcnetwork/care#1803]
Sequentially building both takes more than 8 minutes.
Improve our github actions pipeline to run builds in separate jobs

**Comment by balaji-sivasakthi** [comment]
@sainak, does the Makefile help spin up the container? If so, why would we need to run arm and x86 builds? Could you explain in more detail where we should use it?

**Comment by sainak** [comment]
> @sainak, does the Makefile help spin up the container? If so, why would we need to run arm and x86 builds? Could you explain in more detail where we should use it?

this is regarding the ci pipelines that we have in github actions, https://github.com/coronasafe/care/blob/master/.github/workflows/deployment.yaml

**Comment by balaji-sivasakthi** [comment]
@sainak Got it! Thank you.

**Comment by ghost** [comment]
@rithviknishad Can I work on this issue ?

**Comment by ghost** [comment]
@rithviknishad  Sir could you please review the PR

**Comment by sainak** [comment]
buildkit already does some parallelization during builds, so the benefits of matrix builds are negligible in the case of just 2 platforms.
