### ISSUE TITLE
Hub and Spoke Structure

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/care#706]
Create relation for hub and spoke structure

Update authorisation filter

**Comment by BlessedRice2004** [comment]
@gigincg If this is still relevant/an issue, may I work on this one?

**Comment by gigincg** [comment]
@JohnLu2004 Thanks for bringing this up. Recent changes have deemed this to be irrelevant.

The Hub and Spoke structure has been built using "Linked Facilities"

And the authorisation has been built using "User Linked Facilities" and "User Home Facility"
