### ISSUE TITLE
Inventory unexpectedly marked as Low Stock 

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/care#725]
Creating a PPE Inventory, without having a Minimum Quantity marks it as Low Stock. This shouldn't be the case

**Comment by iamsdas** [comment]
@gigincg is this issue still valid? I am unable to reproduce this issue locally.
(I tried creating a new inventory without specifying the `min_quantity` using the swagger UI. The resulting inventory summary does not have low stock)
![Screenshot_20220510_202231](https://user-images.githubusercontent.com/26461855/167658004-fbd02fe9-b367-43f2-a624-b80db8aca4e7.png)

**Comment by gigincg** [comment]
@nihal467 had replicated it again in #2437

**Comment by suhani221** [comment]
has this issue been resolved?

**Comment by slimkevo** [comment]
Can I be assigned this issue?

**Comment by Harsh-D-2004** [comment]
@gigincg 
Is this resolved or can i be assigned this?
