### ISSUE TITLE
ABDM Integration

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/care#895]
Pre-requisites

- [x] #893 
- [x] #700

Milestones
- [x] #1100
- [x] #1118
- [x] #1119
- [x] #1120

**Comment by khavinshankar** [comment]
Resolved

**Comment by priyanshu14041998** [comment]
Could you provide me Roadmap for Milestone 2

**Comment by singhtanuj913-stack** [comment]
"Hi, I'm evaluating CARE HMIS for white-labeling for small clinics in India. ABDM backend (M1-M4) is working with care_abdm plugin. Is ABHA linking UI available in frontend? Which branch should I check for ABDM frontend features?"
